language: php

php:
  - 5.4

env:
  - SYMFONY_VERSION: 2.1.*
  - SYMFONY_VERSION: 2.2.*
  - SYMFONY_VERSION: 2.3.*
  - SYMFONY_VERSION: 2.4.*
  - SYMFONY_VERSION: 2.5.*@dev

before_script:
  - composer require symfony/framework-bundle:${SYMFONY_VERSION}

notifications:
  email: matthiasnoback@gmail.com